### ISSUE TITLE
Decals being all messed up, Already tried singling out mods.

### ISSUE THREAD

**Issue by ghost** [benjee10/Shuttle-Orbiter-Construction-Kit#17]
![screenshot100](https://github.com/benjee10/Shuttle-Orbiter-Construction-Kit/assets/132978461/4ef5f16d-a0f2-4135-87c5-4589175738e2)
![screenshot102](https://github.com/benjee10/Shuttle-Orbiter-Construction-Kit/assets/132978461/fe50fa92-f933-448b-90df-7caaf2182031)
![screenshot103](https://github.com/benjee10/Shuttle-Orbiter-Construction-Kit/assets/132978461/c525e208-6ad7-48be-917e-c5d8e23e1bbb)

**Comment by benjee10** [comment]
It looks like you are using a Textures Unlimited config such as Magpie, which indiscriminately changes the shaders used on models (breaking anything that relies on transparency such as decals). I can't provide support on this beyond suggesting removing the config, as it's on the config author to provide compatibility with other mods.

**Comment by ghost** [comment]
> It looks like you are using a Textures Unlimited config such as Magpie, which indiscriminately changes the shaders used on models (breaking anything that relies on transparency such as decals). I can't provide support on this beyond suggesting removing the config, as it's on the config author to provide compatibility with other mods.

Oh i see, alright thanks man!
