### ISSUE TITLE
CKAN Install - No Right Wing for OV-100 delta wing. Only the left shows despite symmetry.

### ISSUE THREAD

**Issue by ZoeESummers** [benjee10/Shuttle-Orbiter-Construction-Kit#18]
I've uninstalled the mod, reloaded KSP to check it was gone, then quit KSP and used CKAN to install Shuttle Orbiter Construction Kit + Shuttle Orbiter Construction Kit Recolored + Shuttle Lifting Body but I am still unable to get the stbd wing to appear.

**Comment by benjee10** [comment]
The wing orientation is a part switch due to limitations with how the game handles symmetry and attachment nodes. Ensure you have B9PartSwitch installed - you should be able to right click on the part and change the orientation.

**Comment by ZoeESummers** [comment]
Wow, thank you for the fast response. I do have B9PartSwitch installed and enabled because it was required by the Stockalike Station Mod (amazing mod).

I'll look at right clicking it (never had to do that before but I'm quite new to KSP). 

Thanks

**Comment by ZoeESummers** [comment]
Yup, that was it. Thank you so much!

**Comment by benjee10** [comment]
No problem!
