### ISSUE TITLE
how to do custom shuttle names on the winds and foward fusealge section

### ISSUE THREAD

**Issue by Unavailable14** [benjee10/Shuttle-Orbiter-Construction-Kit#19]
i went into the file with a text editor and changed reliant to advantage (the name i want) and started game and it kept it as reliant even in text editor it still says advantage how do i do this ??????

**Comment by Kiverix** [comment]
did you save the edits?

**Comment by benjee10** [comment]
In order to change the names you will need to modify the texture file. Changing the name in the config will only change the name of the B9 variant. 

Instructions are available here: https://github.com/benjee10/Shuttle-Orbiter-Construction-Kit/blob/master/Extras/INSTALLATION%20INSTRUCTIONS.txt
